comment: false
coverage:
  range: 60..80
  status:
    project: off
    patch: off
ignore:
  - forui/lib/src/theme/theme_data.dart # Mostly configuration
  - forui/lib/src/theme/themes.dart # Mostly configuration