include: package:flint/analysis_options.flutter.yaml
analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore # Temporary ignore until deprecated members are removed.
    implicit_call_tearoffs: ignore
    prefer_asserts_with_message: ignore
    unused_result: ignore

linter:
  rules:
    - use_key_in_widget_constructors
