include: package:flint/analysis_options.flutter.yaml
analyzer:
  errors:
    implicit_call_tearoffs: ignore
    prefer_asserts_with_message: ignore
    unused_result: ignore

linter:
  rules:
    - use_key_in_widget_constructors
