arb-dir: lib/l10n
template-arb-file: f_en.arb
format: true
header: |
  // dart format off
  // coverage:ignore-file
output-dir: lib/src/localizations
output-localization-file: localizations.dart
output-class: FLocalizations
untranslated-messages-file: .i10n.txt