import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

import 'map.dart';

final emitter = DartEmitter();
final formatter = DartFormatter(languageVersion: Version(3, 7, 0), pageWidth: 120);

const header = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// **************************************************************************
// forui
// **************************************************************************
//
// ignore_for_file: type=lint
// ignore_for_file: deprecated_member_use

/// 
''';

String emit(Map<String, Fragment> fragments) {
  final registry =
      LibraryBuilder()
        ..comments.addAll([header])
        ..body.addAll([
          (EnumBuilder()
                ..docs.addAll([
                  '/// The registry for all styles in Forui. This was generated by tool/style_preprocessor.',
                ])
                ..name = 'Registry'
                ..values.addAll([
                  for (final MapEntry(:key, value: fragment) in fragments.entries)
                    (EnumValueBuilder()
                          ..name = key.toLowerCase()
                          ..arguments.addAll([
                            literalBool(fragment.public),
                            literalNum(fragment.position),
                            literalString(fragment.source),
                            literalList(fragment.closure, refer('String')),
                          ]))
                        .build(),
                ])
                ..fields.addAll([
                  (FieldBuilder()
                        ..docs.addAll(['/// True if the style is a top-level style in FThemeData.'])
                        ..name = 'public'
                        ..type = refer('bool')
                        ..modifier = FieldModifier.final$)
                      .build(),
                  (FieldBuilder()
                        ..docs.addAll([
                          '/// The position, inclusive, in the source to add an _, to make the function private.',
                        ])
                        ..name = 'position'
                        ..type = refer('int')
                        ..modifier = FieldModifier.final$)
                      .build(),
                  (FieldBuilder()
                        ..docs.addAll(['/// The function to generate.'])
                        ..name = 'source'
                        ..type = refer('String')
                        ..modifier = FieldModifier.final$)
                      .build(),
                  (FieldBuilder()
                        ..docs.addAll([
                          '/// The functions, including itself, needed to generate a fully compilable style.',
                        ])
                        ..name = 'closure'
                        ..type = refer('List<String>')
                        ..modifier = FieldModifier.final$)
                      .build(),
                ])
                ..constructors.add(
                  (ConstructorBuilder()
                        ..constant = true
                        ..requiredParameters.addAll([
                          Parameter((p) => p..name = 'this.public'),
                          Parameter((p) => p..name = 'this.position'),
                          Parameter((p) => p..name = 'this.source'),
                          Parameter((p) => p..name = 'this.closure'),
                        ]))
                      .build(),
                ))
              .build(),
        ]);

  return formatter.format(registry.build().accept(emitter).toString());
}
