include: package:flint/analysis_options.flutter.yaml
analyzer:
  errors:
    diagnostic_describe_all_properties: ignore
    implicit_call_tearoffs: ignore
    public_member_api_docs: ignore
    unused_result: ignore