name: forui_assets
description: >
  Companion assets for Forui, a UI library for Flutter that provides a set of minimalistic widgets heavily 
  inspired by Shadcn/ui.
version: 0.1.0
homepage: https://forui.dev/
documentation: https://forui.dev/docs
repository: https://github.com/forus-labs/forui
issue_tracker: https://github.com/forus-labs/forui/issues
topics:
  - assets
  - ui
  - widget

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nitrogen_types: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.0
  flint: ^2.8.1
  nitrogen: ^0.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/

nitrogen:
  package: true
  prefix: 'F'
  flutter-extension: false
