name: forui_assets
description: Companion assets for Forui, a set of beautifully designed, minimalistic widgets for desktop & touch devices.
version: 0.11.0
homepage: https://forui.dev/
documentation: https://forui.dev/docs
repository: https://github.com/forus-labs/forui/tree/main/forui_assets
issue_tracker: https://github.com/forus-labs/forui/issues
topics:
  - assets
  - ui
  - widget

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  nitrogen_types: ^0.4.0

dev_dependencies:
  code_builder: ^4.10.0
  dart_style: ^3.0.0
  html: ^0.15.0
  pub_semver: ^2.1.5
  sugar: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#
## The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: ForuiLucideIcons
      fonts:
        - asset: assets/lucide.ttf
