name: forui_assets
description: Companion assets for Forui, a set of beautifully designed, minimalistic widgets for desktop & touch devices.
version: 0.9.1
homepage: https://forui.dev/
documentation: https://forui.dev/docs
repository: https://github.com/forus-labs/forui/tree/main/forui_assets
issue_tracker: https://github.com/forus-labs/forui/issues
topics:
  - assets
  - ui
  - widget

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  nitrogen_types: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.0
  nitrogen: ^0.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/
