// ignore_for_file: avoid_dynamic_calls

import 'dart:convert';
import 'dart:io';

final List<(String, String)> locales = [
  ('af', 'Soek'),
  ('am', 'ፍለጋ'),
  ('ar', 'بحث'),
  ('as', 'সন্ধান কৰক'),
  ('az', 'Axtarış'),
  ('be', 'Пошук'),
  ('bg', 'Търсене'),
  ('bn', 'অনুসন্ধান'),
  ('bs', 'Pretraga'),
  ('ca', 'Cerca'),
  ('cs', 'Hledat'),
  ('cy', 'Chwilio'),
  ('da', 'Søg'),
  ('de', 'Suchen'),
  ('de_CH', 'Suchen'),
  ('el', 'Αναζήτηση'),
  ('en', 'Search'),
  ('en_AU', 'Search'),
  ('en_CA', 'Search'),
  ('en_GB', 'Search'),
  ('en_IE', 'Search'),
  ('en_IN', 'Search'),
  ('en_NZ', 'Search'),
  ('en_SG', 'Search'),
  ('en_ZA', 'Search'),
  ('es', 'Buscar'),
  ('es_419', 'Buscar'),
  ('es_AR', 'Buscar'),
  ('es_BO', 'Buscar'),
  ('es_CL', 'Buscar'),
  ('es_CO', 'Buscar'),
  ('es_CR', 'Buscar'),
  ('es_DO', 'Buscar'),
  ('es_EC', 'Buscar'),
  ('es_GT', 'Buscar'),
  ('es_HN', 'Buscar'),
  ('es_MX', 'Buscar'),
  ('es_NI', 'Buscar'),
  ('es_PA', 'Buscar'),
  ('es_PE', 'Buscar'),
  ('es_PR', 'Buscar'),
  ('es_PY', 'Buscar'),
  ('es_SV', 'Buscar'),
  ('es_US', 'Buscar'),
  ('es_UY', 'Buscar'),
  ('es_VE', 'Buscar'),
  ('et', 'Otsi'),
  ('eu', 'Bilatu'),
  ('fa', 'جستجو'),
  ('fi', 'Haku'),
  ('fil', 'Maghanap'),
  ('fr', 'Rechercher'),
  ('fr_CA', 'Rechercher'),
  ('gl', 'Buscar'),
  ('gsw', 'Sueche'),
  ('gu', 'શોધો'),
  ('he', 'חיפוש'),
  ('hi', 'खोजें'),
  ('hr', 'Pretraži'),
  ('hu', 'Keresés'),
  ('hy', 'Որոնել'),
  ('id', 'Cari'),
  ('is', 'Leita'),
  ('it', 'Cerca'),
  ('ja', '検索'),
  ('ka', 'ძიება'),
  ('kk', 'Іздеу'),
  ('km', 'ស្វែងរក'),
  ('kn', 'ಹುಡುಕಿ'),
  ('ko', '검색'),
  ('ky', 'Издөө'),
  ('lo', 'ຊອກຫາ'),
  ('lt', 'Ieškoti'),
  ('lv', 'Meklēt'),
  ('mk', 'Пребарување'),
  ('ml', 'തിരയുക'),
  ('mn', 'Хайх'),
  ('mr', 'शोधा'),
  ('ms', 'Cari'),
  ('my', 'ရှာဖွေရန်'),
  ('nb', 'Søk'),
  ('ne', 'खोज्नुहोस्'),
  ('nl', 'Zoeken'),
  ('no', 'Søk'),
  ('or', 'ସନ୍ଧାନ କରନ୍ତୁ'),
  ('pa', 'ਖੋਜ'),
  ('pl', 'Szukaj'),
  ('ps', 'لټون'),
  ('pt', 'Pesquisar'),
  ('pt_PT', 'Pesquisar'),
  ('ro', 'Căutare'),
  ('ru', 'Поиск'),
  ('si', 'සොයන්න'),
  ('sk', 'Hľadať'),
  ('sl', 'Iskanje'),
  ('sq', 'Kërko'),
  ('sr', 'Претрага'),
  ('sr_Latn', 'Pretraga'),
  ('sv', 'Sök'),
  ('sw', 'Tafuta'),
  ('ta', 'தேடு'),
  ('te', 'శోధించు'),
  ('th', 'ค้นหา'),
  ('tl', 'Maghanap'),
  ('tr', 'Ara'),
  ('uk', 'Пошук'),
  ('ur', 'تلاش کریں'),
  ('uz', 'Qidirish'),
  ('vi', 'Tìm kiếm'),
  ('zh', '搜索'),
  ('zh_HK', '搜尋'),
  ('zh_TW', '搜尋'),
  ('zu', 'Sesha'),
];

void main() {
  const key = 'selectSearchHint';

  for (final (locale, value) in locales) {
    final arb = File('lib/l10n/f_$locale.arb');
    if (locale == 'en') {
      continue;
    }

    final data = json.decode(arb.readAsStringSync());
    data[key] = value;

    arb.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(data));
  }
}
