// ignore_for_file: avoid_dynamic_calls

import 'dart:convert';
import 'dart:io';

final List<(String, String)> locales = [
  ('af', 'Rol af'),
  ('am', 'ወደ ታች ሸብልል'),
  ('ar', 'التمرير لأسفل'),
  ('as', 'তললৈ স্ক্ৰল কৰক'),
  ('az', 'Aşağı sürüşdür'),
  ('be', 'Прагартаць уніз'),
  ('bg', 'Превъртане надолу'),
  ('bn', 'নিচে স্ক্রোল করুন'),
  ('bs', 'Pomjerite prema dolje'),
  ('ca', 'Desplaça avall'),
  ('cs', 'Posunout dolů'),
  ('cy', 'Sgrolio i lawr'),
  ('da', 'Rul ned'),
  ('de', 'Nach unten scrollen'),
  ('de_CH', 'Nach unten scrollen'),
  ('el', 'Κύλιση προς τα κάτω'),
  ('en', 'Scroll down'),
  ('en_AU', 'Scroll down'),
  ('en_CA', 'Scroll down'),
  ('en_GB', 'Scroll down'),
  ('en_IE', 'Scroll down'),
  ('en_IN', 'Scroll down'),
  ('en_NZ', 'Scroll down'),
  ('en_SG', 'Scroll down'),
  ('en_ZA', 'Scroll down'),
  ('es', 'Desplazarse hacia abajo'),
  ('es_419', 'Desplazarse hacia abajo'),
  ('es_AR', 'Desplazarse hacia abajo'),
  ('es_BO', 'Desplazarse hacia abajo'),
  ('es_CL', 'Desplazarse hacia abajo'),
  ('es_CO', 'Desplazarse hacia abajo'),
  ('es_CR', 'Desplazarse hacia abajo'),
  ('es_DO', 'Desplazarse hacia abajo'),
  ('es_EC', 'Desplazarse hacia abajo'),
  ('es_GT', 'Desplazarse hacia abajo'),
  ('es_HN', 'Desplazarse hacia abajo'),
  ('es_MX', 'Desplazarse hacia abajo'),
  ('es_NI', 'Desplazarse hacia abajo'),
  ('es_PA', 'Desplazarse hacia abajo'),
  ('es_PE', 'Desplazarse hacia abajo'),
  ('es_PR', 'Desplazarse hacia abajo'),
  ('es_PY', 'Desplazarse hacia abajo'),
  ('es_SV', 'Desplazarse hacia abajo'),
  ('es_US', 'Desplazarse hacia abajo'),
  ('es_UY', 'Desplazarse hacia abajo'),
  ('es_VE', 'Desplazarse hacia abajo'),
  ('et', 'Keri alla'),
  ('eu', 'Egin behera'),
  ('fa', 'پیمایش به پایین'),
  ('fi', 'Vieritä alas'),
  ('fil', 'Mag-scroll pababa'),
  ('fr', 'Faire défiler vers le bas'),
  ('fr_CA', 'Faire défiler vers le bas'),
  ('gl', 'Desprazarse cara abaixo'),
  ('gsw', 'Nach unde scrolle'),
  ('gu', 'નીચે સ્ક્રોલ કરો'),
  ('he', 'גלול למטה'),
  ('hi', 'नीचे स्क्रॉल करें'),
  ('hr', 'Pomakni prema dolje'),
  ('hu', 'Görgetés lefelé'),
  ('hy', 'Ոլորել ներքև'),
  ('id', 'Gulir ke bawah'),
  ('is', 'Fletta niður'),
  ('it', 'Scorri verso il basso'),
  ('ja', '下にスクロール'),
  ('ka', 'ქვემოთ გადაადგილება'),
  ('kk', 'Төмен айналдыру'),
  ('km', 'រមូរចុះក្រោម'),
  ('kn', 'ಕೆಳಗೆ ಸ್ಕ್ರಾಲ್ ಮಾಡಿ'),
  ('ko', '아래로 스크롤'),
  ('ky', 'Ылдый сыдыруу'),
  ('lo', 'ເລື່ອນລົງ'),
  ('lt', 'Slinkti žemyn'),
  ('lv', 'Ritināt uz leju'),
  ('mk', 'Лизгај надолу'),
  ('ml', 'താഴേക്ക് സ്ക്രോൾ ചെയ്യുക'),
  ('mn', 'Доош гүйлгэх'),
  ('mr', 'खाली स्क्रोल करा'),
  ('ms', 'Tatal ke bawah'),
  ('my', 'အောက်သို့ပွတ်ဆွဲရန်'),
  ('nb', 'Rull ned'),
  ('ne', 'तल स्क्रोल गर्नुहोस्'),
  ('nl', 'Omlaag scrollen'),
  ('no', 'Rull ned'),
  ('or', 'ତଳକୁ ସ୍କ୍ରୋଲ କରନ୍ତୁ'),
  ('pa', 'ਹੇਠਾਂ ਸਕ੍ਰੋਲ ਕਰੋ'),
  ('pl', 'Przewiń w dół'),
  ('ps', 'ښکته سکرول کړئ'),
  ('pt', 'Rolar para baixo'),
  ('pt_PT', 'Deslocar para baixo'),
  ('ro', 'Derulează în jos'),
  ('ru', 'Прокрутить вниз'),
  ('si', 'පහළට අනුචලනය කරන්න'),
  ('sk', 'Posunúť nadol'),
  ('sl', 'Pomik navzdol'),
  ('sq', 'Lëviz poshtë'),
  ('sr', 'Померите надоле'),
  ('sr_Latn', 'Pomerite nadole'),
  ('sv', 'Rulla nedåt'),
  ('sw', 'Sogeza chini'),
  ('ta', 'கீழே உருட்டு'),
  ('te', 'క్రిందికి స్క్రోల్ చేయండి'),
  ('th', 'เลื่อนลง'),
  ('tl', 'Mag-scroll pababa'),
  ('tr', 'Aşağı kaydır'),
  ('uk', 'Прокрутити вниз'),
  ('ur', 'نیچے سکرول کریں'),
  ('uz', 'Pastga aylantirish'),
  ('vi', 'Cuộn xuống'),
  ('zh', '向下滚动'),
  ('zh_HK', '向下捲動'),
  ('zh_TW', '向下捲動'),
  ('zu', 'Skrola phansi'),
];

void main() {
  const key = 'selectScrollDownSemanticsLabel';

  for (final (locale, value) in locales) {
    final arb = File('lib/l10n/f_$locale.arb');
    if (locale == 'en') {
      continue;
    }

    final data = json.decode(arb.readAsStringSync());
    data[key] = value;

    arb.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(data));
  }
}
