// ignore_for_file: avoid_dynamic_calls

import 'dart:convert';
import 'dart:io';

final List<(String, String)> locales = [
  ('af', 'Geen passende resultate nie.'),
  ('am', 'ምንም ተዛማጅ ውጤቶች የሉም።'),
  ('ar', 'لا توجد نتائج مطابقة.'),
  ('as', 'কোনো মিল থকা ফলাফল নাই।'),
  ('az', 'Uyğun nəticə tapılmadı.'),
  ('be', 'Няма адпаведных вынікаў.'),
  ('bg', 'Няма съвпадащи резултати.'),
  ('bn', 'কোন মিলে যাওয়া ফলাফল নেই।'),
  ('bs', 'Nema odgovarajućih rezultata.'),
  ('ca', 'No s\'han trobat resultats coincidents.'),
  ('cs', 'Žádné odpovídající výsledky.'),
  ('cy', 'Dim canlyniadau cyfatebol.'),
  ('da', 'Ingen matchende resultater.'),
  ('de', 'Keine übereinstimmenden Ergebnisse.'),
  ('de_CH', 'Keine übereinstimmenden Ergebnisse.'),
  ('el', 'Δεν βρέθηκαν αποτελέσματα.'),
  ('en', 'No matching results.'),
  ('en_AU', 'No matching results.'),
  ('en_CA', 'No matching results.'),
  ('en_GB', 'No matching results.'),
  ('en_IE', 'No matching results.'),
  ('en_IN', 'No matching results.'),
  ('en_NZ', 'No matching results.'),
  ('en_SG', 'No matching results.'),
  ('en_ZA', 'No matching results.'),
  ('es', 'No hay resultados coincidentes.'),
  ('es_419', 'No hay resultados coincidentes.'),
  ('es_AR', 'No hay resultados coincidentes.'),
  ('es_BO', 'No hay resultados coincidentes.'),
  ('es_CL', 'No hay resultados coincidentes.'),
  ('es_CO', 'No hay resultados coincidentes.'),
  ('es_CR', 'No hay resultados coincidentes.'),
  ('es_DO', 'No hay resultados coincidentes.'),
  ('es_EC', 'No hay resultados coincidentes.'),
  ('es_GT', 'No hay resultados coincidentes.'),
  ('es_HN', 'No hay resultados coincidentes.'),
  ('es_MX', 'No hay resultados coincidentes.'),
  ('es_NI', 'No hay resultados coincidentes.'),
  ('es_PA', 'No hay resultados coincidentes.'),
  ('es_PE', 'No hay resultados coincidentes.'),
  ('es_PR', 'No hay resultados coincidentes.'),
  ('es_PY', 'No hay resultados coincidentes.'),
  ('es_SV', 'No hay resultados coincidentes.'),
  ('es_US', 'No hay resultados coincidentes.'),
  ('es_UY', 'No hay resultados coincidentes.'),
  ('es_VE', 'No hay resultados coincidentes.'),
  ('et', 'Sobivaid tulemusi pole.'),
  ('eu', 'Ez dago bat datorren emaitzarik.'),
  ('fa', 'نتیجه‌ای مطابقت ندارد.'),
  ('fi', 'Ei vastaavia tuloksia.'),
  ('fil', 'Walang mga tumutugmang resulta.'),
  ('fr', 'Aucun résultat correspondant.'),
  ('fr_CA', 'Aucun résultat correspondant.'),
  ('gl', 'Non hai resultados coincidentes.'),
  ('gsw', 'Kei passendi Ergebnis.'),
  ('gu', 'કોઈ મેળ ખાતાં પરિણામો નથી.'),
  ('he', 'אין תוצאות תואמות.'),
  ('hi', 'कोई मिलान परिणाम नहीं।'),
  ('hr', 'Nema podudarajućih rezultata.'),
  ('hu', 'Nincs megfelelő találat.'),
  ('hy', 'Համապատասխան արդյունքներ չկան։'),
  ('id', 'Tidak ada hasil yang cocok.'),
  ('is', 'Engar samsvarandi niðurstöður.'),
  ('it', 'Nessun risultato corrispondente.'),
  ('ja', '一致する結果がありません。'),
  ('ka', 'შესაბამისი შედეგები არ არის.'),
  ('kk', 'Сәйкес нәтижелер жоқ.'),
  ('km', 'គ្មានលទ្ធផលដែលត្រូវគ្នាទេ។'),
  ('kn', 'ಹೊಂದಾಣಿಕೆಯಾಗುವ ಫಲಿತಾಂಶಗಳಿಲ್ಲ.'),
  ('ko', '일치하는 결과가 없습니다.'),
  ('ky', 'Дал келген натыйжалар жок.'),
  ('lo', 'ບໍ່ມີຜົນການຊອກຫາທີ່ກົງກັນ.'),
  ('lt', 'Jokių atitinkančių rezultatų.'),
  ('lv', 'Nav atbilstošu rezultātu.'),
  ('mk', 'Нема совпаѓачки резултати.'),
  ('ml', 'പൊരുത്തപ്പെടുന്ന ഫലങ്ങളൊന്നുമില്ല.'),
  ('mn', 'Тохирох үр дүн олдсонгүй.'),
  ('mr', 'कोणतेही जुळणारे परिणाम नाहीत.'),
  ('ms', 'Tiada hasil yang sepadan.'),
  ('my', 'တူညီသည့်ရလဒ်များမရှိပါ။'),
  ('nb', 'Ingen samsvarende resultater.'),
  ('ne', 'कुनै मिल्दो परिणामहरू छैनन्।'),
  ('nl', 'Geen overeenkomende resultaten.'),
  ('no', 'Ingen samsvarende resultater.'),
  ('or', 'କୌଣସି ମେଳଖାଉଥିବା ଫଳାଫଳ ନାହିଁ।'),
  ('pa', 'ਕੋਈ ਮੇਲ ਖਾਂਦੇ ਨਤੀਜੇ ਨਹੀਂ ਹਨ।'),
  ('pl', 'Brak pasujących wyników.'),
  ('ps', 'هیڅ سمون لرونکي پایلې نشته.'),
  ('pt', 'Nenhum resultado correspondente.'),
  ('pt_PT', 'Sem resultados correspondentes.'),
  ('ro', 'Niciun rezultat care să se potrivească.'),
  ('ru', 'Нет совпадающих результатов.'),
  ('si', 'ගැලපෙන ප්‍රතිඵල නොමැත.'),
  ('sk', 'Žiadne zodpovedajúce výsledky.'),
  ('sl', 'Ni ujemajočih se rezultatov.'),
  ('sq', 'Nuk ka rezultate përputhëse.'),
  ('sr', 'Нема подударајућих резултата.'),
  ('sr_Latn', 'Nema podudarajućih rezultata.'),
  ('sv', 'Inga matchande resultat.'),
  ('sw', 'Hakuna matokeo yanayolingana.'),
  ('ta', 'பொருந்தும் முடிவுகள் இல்லை.'),
  ('te', 'సరిపోలే ఫలితాలు లేవు.'),
  ('th', 'ไม่มีผลลัพธ์ที่ตรงกัน'),
  ('tl', 'Walang mga tumutugmang resulta.'),
  ('tr', 'Eşleşen sonuç yok.'),
  ('uk', 'Немає відповідних результатів.'),
  ('ur', 'کوئی مماثل نتائج نہیں۔'),
  ('uz', 'Mos keladigan natijalar yo\'q.'),
  ('vi', 'Không có kết quả phù hợp.'),
  ('zh', '没有匹配结果。'),
  ('zh_HK', '沒有匹配結果。'),
  ('zh_TW', '沒有匹配結果。'),
  ('zu', 'Ayikho imiphumela efanayo.'),
];
void main() {
  const key = 'selectSearchNoResults';

  for (final (locale, value) in locales) {
    final arb = File('lib/l10n/f_$locale.arb');
    if (locale == 'en') {
      continue;
    }

    final data = json.decode(arb.readAsStringSync());
    data[key] = value;

    arb.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(data));
  }
}
