import 'package:flutter/gestures.dart';
import 'package:flutter/widgets.dart';

import 'package:forui/forui.dart';
import 'package:forui/src/widgets/select_menu_tile.dart';

/// A marker interface which denotes that mixed-in widgets can be used in a [FTileGroup].
mixin FTileMixin on Widget {
  /// {@macro forui.widgets.FSelectMenuTile.new}
  ///
  /// This function is a shorthand for [FSelectMenuTile.new].
  static FSelectMenuTile<T> selectMenu<T>({
    required Widget title,
    required List<FSelectTile<T>> menu,
    FMultiValueControl<T>? selectControl,
    FPopoverControl popoverControl = const .managed(),
    ScrollController? scrollController,
    FSelectMenuTileStyle Function(FSelectMenuTileStyle style)? style,
    double? cacheExtent,
    double maxHeight = .infinity,
    DragStartBehavior dragStartBehavior = .start,
    ScrollPhysics physics = const ClampingScrollPhysics(),
    FItemDivider divider = .full,
    AlignmentGeometry menuAnchor = .topRight,
    AlignmentGeometry tileAnchor = .bottomRight,
    FPortalSpacing menuSpacing = const .spacing(4),
    FPortalOverflow menuOverflow = .flip,
    Offset menuOffset = .zero,
    FPopoverHideRegion menuHideRegion = .excludeChild,
    VoidCallback? menuOnTapHide,
    Object? menuGroupId,
    bool autoHide = true,
    Widget? label,
    Widget? description,
    bool autofocus = false,
    FocusScopeNode? menuFocusNode,
    ValueChanged<bool>? menuOnFocusChange,
    TraversalEdgeBehavior? menuTraversalEdgeBehavior,
    String? menuBarrierSemanticsLabel,
    bool menuBarrierSemanticsDismissible = true,
    String? semanticsLabel,
    Widget? prefix,
    Widget? subtitle,
    ValueWidgetBuilder<Set<T>> detailsBuilder = defaultSelectMenuTileBuilder,
    Widget? details,
    Widget? suffix,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget Function(BuildContext context, String message) errorBuilder = FFormFieldProperties.defaultErrorBuilder,
    FormFieldSetter<Set<T>>? onSaved,
    VoidCallback? onReset,
    FormFieldValidator<Set<T>>? validator,
    String? forceErrorText,
    bool enabled = true,
    AutovalidateMode autovalidateMode = .disabled,
    Key? key,
  }) => .new(
    title: title,
    menu: menu,
    selectControl: selectControl,
    popoverControl: popoverControl,
    scrollController: scrollController,
    style: style,
    cacheExtent: cacheExtent,
    maxHeight: maxHeight,
    dragStartBehavior: dragStartBehavior,
    physics: physics,
    divider: divider,
    menuAnchor: menuAnchor,
    tileAnchor: tileAnchor,
    menuSpacing: menuSpacing,
    menuOverflow: menuOverflow,
    menuOffset: menuOffset,
    menuHideRegion: menuHideRegion,
    menuOnTapHide: menuOnTapHide,
    menuGroupId: menuGroupId,
    autoHide: autoHide,
    label: label,
    description: description,
    autofocus: autofocus,
    menuFocusNode: menuFocusNode,
    menuOnFocusChange: menuOnFocusChange,
    menuTraversalEdgeBehavior: menuTraversalEdgeBehavior,
    menuBarrierSemanticsLabel: menuBarrierSemanticsLabel,
    menuBarrierSemanticsDismissible: menuBarrierSemanticsDismissible,
    semanticsLabel: semanticsLabel,
    prefix: prefix,
    subtitle: subtitle,
    detailsBuilder: detailsBuilder,
    details: details,
    suffix: suffix,
    shortcuts: shortcuts,
    actions: actions,
    errorBuilder: errorBuilder,
    onSaved: onSaved,
    onReset: onReset,
    validator: validator,
    forceErrorText: forceErrorText,
    enabled: enabled,
    autovalidateMode: autovalidateMode,
    key: key,
  );

  /// {@macro forui.widgets.FSelectMenuTile.fromMap}
  ///
  /// This function is a shorthand for [FSelectMenuTile.fromMap].
  static FSelectMenuTile<T> selectMenuFromMap<T>(
    Map<String, T> menu, {
    required Text title,
    FMultiValueControl<T>? selectControl,
    FPopoverControl popoverControl = const .managed(),
    ScrollController? scrollController,
    FSelectMenuTileStyle Function(FSelectMenuTileStyle style)? style,
    double? cacheExtent,
    double maxHeight = .infinity,
    DragStartBehavior dragStartBehavior = .start,
    ScrollPhysics physics = const ClampingScrollPhysics(),
    FItemDivider divider = .full,
    AlignmentGeometry menuAnchor = .topRight,
    AlignmentGeometry tileAnchor = .bottomRight,
    FPortalSpacing menuSpacing = const .spacing(4),
    FPortalOverflow menuOverflow = .flip,
    Offset menuOffset = .zero,
    FPopoverHideRegion menuHideRegion = .excludeChild,
    VoidCallback? menuOnTapHide,
    Object? menuGroupId,
    bool autoHide = true,
    Widget? label,
    Widget? description,
    bool autofocus = false,
    FocusScopeNode? menuFocusNode,
    ValueChanged<bool>? menuOnFocusChange,
    TraversalEdgeBehavior? menuTraversalEdgeBehavior,
    String? menuBarrierSemanticsLabel,
    bool menuBarrierSemanticsDismissible = true,
    String? semanticsLabel,
    Widget? prefix,
    Widget? subtitle,
    ValueWidgetBuilder<Set<T>> detailsBuilder = defaultSelectMenuTileBuilder,
    Widget? details,
    Widget? suffix,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget Function(BuildContext context, String message) errorBuilder = FFormFieldProperties.defaultErrorBuilder,
    FormFieldSetter<Set<T>>? onSaved,
    VoidCallback? onReset,
    FormFieldValidator<Set<T>>? validator,
    String? forceErrorText,
    bool enabled = true,
    AutovalidateMode autovalidateMode = .disabled,
    Key? key,
  }) => .fromMap(
    menu,
    title: title,
    selectControl: selectControl,
    popoverControl: popoverControl,
    scrollController: scrollController,
    style: style,
    cacheExtent: cacheExtent,
    maxHeight: maxHeight,
    dragStartBehavior: dragStartBehavior,
    physics: physics,
    divider: divider,
    menuAnchor: menuAnchor,
    tileAnchor: tileAnchor,
    menuSpacing: menuSpacing,
    menuOverflow: menuOverflow,
    menuOffset: menuOffset,
    menuHideRegion: menuHideRegion,
    menuOnTapHide: menuOnTapHide,
    menuGroupId: menuGroupId,
    autoHide: autoHide,
    label: label,
    description: description,
    autofocus: autofocus,
    menuFocusNode: menuFocusNode,
    menuOnFocusChange: menuOnFocusChange,
    menuTraversalEdgeBehavior: menuTraversalEdgeBehavior,
    menuBarrierSemanticsLabel: menuBarrierSemanticsLabel,
    menuBarrierSemanticsDismissible: menuBarrierSemanticsDismissible,
    semanticsLabel: semanticsLabel,
    prefix: prefix,
    subtitle: subtitle,
    detailsBuilder: detailsBuilder,
    details: details,
    suffix: suffix,
    shortcuts: shortcuts,
    actions: actions,
    errorBuilder: errorBuilder,
    onSaved: onSaved,
    onReset: onReset,
    validator: validator,
    forceErrorText: forceErrorText,
    enabled: enabled,
    autovalidateMode: autovalidateMode,
    key: key,
  );

  /// {@macro forui.widgets.FSelectMenuTile.builder}
  ///
  /// This function is a shorthand for [FSelectMenuTile.builder].
  static FSelectMenuTile<T> selectMenuBuilder<T>({
    required Widget title,
    required FSelectTile<T>? Function(BuildContext context, int index) menuBuilder,
    int? count,
    FMultiValueControl<T>? selectControl,
    FPopoverControl popoverControl = const .managed(),
    ScrollController? scrollController,
    FSelectMenuTileStyle Function(FSelectMenuTileStyle style)? style,
    double? cacheExtent,
    double maxHeight = .infinity,
    DragStartBehavior dragStartBehavior = .start,
    ScrollPhysics physics = const ClampingScrollPhysics(),
    FItemDivider divider = .full,
    AlignmentGeometry menuAnchor = .topRight,
    AlignmentGeometry tileAnchor = .bottomRight,
    FPortalSpacing menuSpacing = const .spacing(4),
    FPortalOverflow menuOverflow = .flip,
    Offset menuOffset = .zero,
    FPopoverHideRegion menuHideRegion = .excludeChild,
    VoidCallback? menuOnTapHide,
    Object? menuGroupId,
    bool autoHide = true,
    Widget? label,
    Widget? description,
    bool autofocus = false,
    FocusScopeNode? menuFocusNode,
    ValueChanged<bool>? menuOnFocusChange,
    TraversalEdgeBehavior? menuTraversalEdgeBehavior,
    String? menuBarrierSemanticsLabel,
    bool menuBarrierSemanticsDismissible = true,
    String? semanticsLabel,
    Widget? prefix,
    Widget? subtitle,
    ValueWidgetBuilder<Set<T>> detailsBuilder = defaultSelectMenuTileBuilder,
    Widget? details,
    Widget? suffix,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget Function(BuildContext context, String message) errorBuilder = FFormFieldProperties.defaultErrorBuilder,
    FormFieldSetter<Set<T>>? onSaved,
    VoidCallback? onReset,
    FormFieldValidator<Set<T>>? validator,
    String? forceErrorText,
    bool enabled = true,
    AutovalidateMode autovalidateMode = .disabled,
    Key? key,
  }) => .builder(
    title: title,
    menuBuilder: menuBuilder,
    count: count,
    selectControl: selectControl,
    popoverControl: popoverControl,
    scrollController: scrollController,
    style: style,
    cacheExtent: cacheExtent,
    maxHeight: maxHeight,
    dragStartBehavior: dragStartBehavior,
    physics: physics,
    divider: divider,
    menuAnchor: menuAnchor,
    tileAnchor: tileAnchor,
    menuSpacing: menuSpacing,
    menuOverflow: menuOverflow,
    menuOffset: menuOffset,
    menuHideRegion: menuHideRegion,
    menuOnTapHide: menuOnTapHide,
    menuGroupId: menuGroupId,
    autoHide: autoHide,
    label: label,
    description: description,
    autofocus: autofocus,
    menuFocusNode: menuFocusNode,
    menuOnFocusChange: menuOnFocusChange,
    menuTraversalEdgeBehavior: menuTraversalEdgeBehavior,
    menuBarrierSemanticsLabel: menuBarrierSemanticsLabel,
    menuBarrierSemanticsDismissible: menuBarrierSemanticsDismissible,
    semanticsLabel: semanticsLabel,
    prefix: prefix,
    subtitle: subtitle,
    detailsBuilder: detailsBuilder,
    details: details,
    suffix: suffix,
    shortcuts: shortcuts,
    actions: actions,
    errorBuilder: errorBuilder,
    onSaved: onSaved,
    onReset: onReset,
    validator: validator,
    forceErrorText: forceErrorText,
    enabled: enabled,
    autovalidateMode: autovalidateMode,
    key: key,
  );

  /// {@macro forui.widgets.FTile.new}
  ///
  /// This function is a shorthand for [FTile.new].
  static FTile tile({
    required Widget title,
    FItemStyle Function(FItemStyle style)? style,
    bool? enabled,
    bool selected = false,
    String? semanticsLabel,
    bool autofocus = false,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    ValueChanged<bool>? onHoverChange,
    ValueChanged<FWidgetStatesDelta>? onStateChange,
    VoidCallback? onPress,
    VoidCallback? onLongPress,
    VoidCallback? onSecondaryPress,
    VoidCallback? onSecondaryLongPress,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget? prefix,
    Widget? subtitle,
    Widget? details,
    Widget? suffix,
    Key? key,
  }) => .new(
    title: title,
    style: style,
    enabled: enabled,
    selected: selected,
    semanticsLabel: semanticsLabel,
    autofocus: autofocus,
    focusNode: focusNode,
    onFocusChange: onFocusChange,
    onHoverChange: onHoverChange,
    onStateChange: onStateChange,
    onPress: onPress,
    onLongPress: onLongPress,
    onSecondaryPress: onSecondaryPress,
    onSecondaryLongPress: onSecondaryLongPress,
    shortcuts: shortcuts,
    actions: actions,
    prefix: prefix,
    subtitle: subtitle,
    details: details,
    suffix: suffix,
    key: key,
  );

  /// {@macro forui.widgets.FTile.raw}
  ///
  /// This function is a shorthand for [FTile.raw].
  static FTile raw({
    required Widget child,
    FItemStyle Function(FItemStyle style)? style,
    bool? enabled,
    bool selected = false,
    String? semanticsLabel,
    bool autofocus = false,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    ValueChanged<bool>? onHoverChange,
    ValueChanged<FWidgetStatesDelta>? onStateChange,
    VoidCallback? onPress,
    VoidCallback? onLongPress,
    VoidCallback? onSecondaryPress,
    VoidCallback? onSecondaryLongPress,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget? prefix,
    Key? key,
  }) => .raw(
    style: style,
    enabled: enabled,
    selected: selected,
    semanticsLabel: semanticsLabel,
    autofocus: autofocus,
    focusNode: focusNode,
    onFocusChange: onFocusChange,
    onHoverChange: onHoverChange,
    onStateChange: onStateChange,
    onPress: onPress,
    onLongPress: onLongPress,
    onSecondaryPress: onSecondaryPress,
    onSecondaryLongPress: onSecondaryLongPress,
    shortcuts: shortcuts,
    actions: actions,
    prefix: prefix,
    key: key,
    child: child,
  );
}
