name: Lint

on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/lint.yaml
      - '**.md'
  pull_request_target:
    paths:
      - .github/workflows/lint.yaml
      - '**.md'

jobs:
  lint:
    name: Lint Markdown URLs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.AUTO_MAID_APP_ID }}
          private_key: ${{ secrets.AUTO_MAID_PRIVATE_KEY }}
      - uses: lycheeverse/lychee-action@v2
        with:
          # GitHub seems to have tightened their secondary rate limits causing previously working checks to fail.
          args: --base . --no-progress './**/*.md' --exclude '^https://www\.github\.com'
          token: ${{ steps.generate-token.outputs.token }}
