name: Samples Build

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - .github/workflows/samples_build.yaml
      - forui/**
      - samples/**

  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/samples_build.yaml
      - forui/**
      - samples/**

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: samples
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: subosito/flutter-action@v2.12.0
        with:
          cache: true

      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: flutter test
      - run: flutter build appbundle --debug --no-pub --no-tree-shake-icons