name: Forui Samples Build

on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/samples_build.yaml
      - samples/**

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: samples

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.16.0
        with:
          cache: true
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
