name: Forui Samples Build

on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/samples_build.yaml
      - forui/**
      - samples/**
  pull_request:
    paths:
      - forui/**
      - samples/**

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: samples
    strategy:
      matrix:
        flutter-version: [ 3.x ]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{ matrix.flutter-version }}
          cache: true
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
