name: Forui Samples Build

on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/samples_build.yaml
      - forui/**
      - samples/**
  pull_request:
    paths:
      - forui/**
      - samples/**

jobs:
  test:
    name: Build & test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: samples
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        flutter-version: [ 3.x ]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: ${{ matrix.flutter-version }}
          cache: true

      - working-directory: forui
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
