import 'package:flutter/widgets.dart';

import 'package:flutter_test/flutter_test.dart';

import 'package:forui/src/foundation/portal/portal_spacing.dart';

void main() {
  for (final (child, portal, expected) in [
    (Alignment.topLeft, Alignment.topLeft, Offset.zero),
    (Alignment.topLeft, Alignment.topCenter, Offset.zero),
    (Alignment.topLeft, Alignment.topRight, const Offset(-1, 0)),
    (Alignment.topLeft, Alignment.centerLeft, Offset.zero),
    (Alignment.topLeft, Alignment.center, Offset.zero),
    (Alignment.topLeft, Alignment.centerRight, const Offset(-1, 0)),
    (Alignment.topLeft, Alignment.bottomLeft, const Offset(0, -1)),
    (Alignment.topLeft, Alignment.bottomCenter, const Offset(0, -1)),
    (Alignment.topLeft, Alignment.bottomRight, const Offset(-1, -1)),
    //
    (Alignment.topCenter, Alignment.topLeft, Offset.zero),
    (Alignment.topCenter, Alignment.topCenter, Offset.zero),
    (Alignment.topCenter, Alignment.topRight, Offset.zero),
    (Alignment.topCenter, Alignment.centerLeft, Offset.zero),
    (Alignment.topCenter, Alignment.center, Offset.zero),
    (Alignment.topCenter, Alignment.centerRight, Offset.zero),
    (Alignment.topCenter, Alignment.bottomLeft, const Offset(0, -1)),
    (Alignment.topCenter, Alignment.bottomCenter, const Offset(0, -1)),
    (Alignment.topCenter, Alignment.bottomRight, const Offset(0, -1)),
    //
    (Alignment.topRight, Alignment.topLeft, const Offset(1, 0)),
    (Alignment.topRight, Alignment.topCenter, Offset.zero),
    (Alignment.topRight, Alignment.topRight, Offset.zero),
    (Alignment.topRight, Alignment.centerLeft, const Offset(1, 0)),
    (Alignment.topRight, Alignment.center, Offset.zero),
    (Alignment.topRight, Alignment.centerRight, Offset.zero),
    (Alignment.topRight, Alignment.bottomLeft, const Offset(1, -1)),
    (Alignment.topRight, Alignment.bottomCenter, const Offset(0, -1)),
    (Alignment.topRight, Alignment.bottomRight, const Offset(0, -1)),
    //
    (Alignment.centerLeft, Alignment.topLeft, Offset.zero),
    (Alignment.centerLeft, Alignment.topCenter, Offset.zero),
    (Alignment.centerLeft, Alignment.topRight, const Offset(-1, 0)),
    (Alignment.centerLeft, Alignment.centerLeft, Offset.zero),
    (Alignment.centerLeft, Alignment.center, Offset.zero),
    (Alignment.centerLeft, Alignment.centerRight, const Offset(-1, 0)),
    (Alignment.centerLeft, Alignment.bottomLeft, Offset.zero),
    (Alignment.centerLeft, Alignment.bottomCenter, Offset.zero),
    (Alignment.centerLeft, Alignment.bottomRight, const Offset(-1, 0)),
    //
    (Alignment.center, Alignment.topLeft, Offset.zero),
    (Alignment.center, Alignment.topCenter, Offset.zero),
    (Alignment.center, Alignment.topRight, Offset.zero),
    (Alignment.center, Alignment.centerLeft, Offset.zero),
    (Alignment.center, Alignment.center, Offset.zero),
    (Alignment.center, Alignment.centerRight, Offset.zero),
    (Alignment.center, Alignment.bottomLeft, Offset.zero),
    (Alignment.center, Alignment.bottomCenter, Offset.zero),
    (Alignment.center, Alignment.bottomRight, Offset.zero),
    //
    (Alignment.centerRight, Alignment.topLeft, const Offset(1, 0)),
    (Alignment.centerRight, Alignment.topCenter, Offset.zero),
    (Alignment.centerRight, Alignment.topRight, Offset.zero),
    (Alignment.centerRight, Alignment.centerLeft, const Offset(1, 0)),
    (Alignment.centerRight, Alignment.center, Offset.zero),
    (Alignment.centerRight, Alignment.centerRight, Offset.zero),
    (Alignment.centerRight, Alignment.bottomLeft, const Offset(1, 0)),
    (Alignment.centerRight, Alignment.bottomCenter, Offset.zero),
    (Alignment.centerRight, Alignment.bottomRight, Offset.zero),
    //
    (Alignment.bottomLeft, Alignment.topLeft, const Offset(0, 1)),
    (Alignment.bottomLeft, Alignment.topCenter, const Offset(0, 1)),
    (Alignment.bottomLeft, Alignment.topRight, const Offset(-1, 1)),
    (Alignment.bottomLeft, Alignment.centerLeft, Offset.zero),
    (Alignment.bottomLeft, Alignment.center, Offset.zero),
    (Alignment.bottomLeft, Alignment.centerRight, const Offset(-1, 0)),
    (Alignment.bottomLeft, Alignment.bottomLeft, Offset.zero),
    (Alignment.bottomLeft, Alignment.bottomCenter, Offset.zero),
    (Alignment.bottomLeft, Alignment.bottomRight, const Offset(-1, 0)),
    //
    (Alignment.bottomCenter, Alignment.topLeft, const Offset(0, 1)),
    (Alignment.bottomCenter, Alignment.topCenter, const Offset(0, 1)),
    (Alignment.bottomCenter, Alignment.topRight, const Offset(0, 1)),
    (Alignment.bottomCenter, Alignment.centerLeft, Offset.zero),
    (Alignment.bottomCenter, Alignment.center, Offset.zero),
    (Alignment.bottomCenter, Alignment.centerRight, Offset.zero),
    (Alignment.bottomCenter, Alignment.bottomLeft, Offset.zero),
    (Alignment.bottomCenter, Alignment.bottomCenter, Offset.zero),
    (Alignment.bottomCenter, Alignment.bottomRight, Offset.zero),
    //
    (Alignment.bottomRight, Alignment.topLeft, const Offset(1, 1)),
    (Alignment.bottomRight, Alignment.topCenter, const Offset(0, 1)),
    (Alignment.bottomRight, Alignment.topRight, const Offset(0, 1)),
    (Alignment.bottomRight, Alignment.centerLeft, const Offset(1, 0)),
    (Alignment.bottomRight, Alignment.center, Offset.zero),
    (Alignment.bottomRight, Alignment.centerRight, Offset.zero),
    (Alignment.bottomRight, Alignment.bottomLeft, const Offset(1, 0)),
    (Alignment.bottomRight, Alignment.bottomCenter, Offset.zero),
    (Alignment.bottomRight, Alignment.bottomRight, Offset.zero),
  ]) {
    test(
      'default portal spacing, diagonals - $child -$portal',
      () => expect(const FPortalSpacing(1, diagonal: true).call(child, portal), expected),
    );
  }

  for (final (child, portal, expected) in [
    (Alignment.topLeft, Alignment.topLeft, Offset.zero),
    (Alignment.topLeft, Alignment.topCenter, Offset.zero),
    (Alignment.topLeft, Alignment.topRight, const Offset(-1, 0)),
    (Alignment.topLeft, Alignment.centerLeft, Offset.zero),
    (Alignment.topLeft, Alignment.center, Offset.zero),
    (Alignment.topLeft, Alignment.centerRight, const Offset(-1, 0)),
    (Alignment.topLeft, Alignment.bottomLeft, const Offset(0, -1)),
    (Alignment.topLeft, Alignment.bottomCenter, const Offset(0, -1)),
    (Alignment.topLeft, Alignment.bottomRight, Offset.zero),
    //
    (Alignment.topCenter, Alignment.topLeft, Offset.zero),
    (Alignment.topCenter, Alignment.topCenter, Offset.zero),
    (Alignment.topCenter, Alignment.topRight, Offset.zero),
    (Alignment.topCenter, Alignment.centerLeft, Offset.zero),
    (Alignment.topCenter, Alignment.center, Offset.zero),
    (Alignment.topCenter, Alignment.centerRight, Offset.zero),
    (Alignment.topCenter, Alignment.bottomLeft, const Offset(0, -1)),
    (Alignment.topCenter, Alignment.bottomCenter, const Offset(0, -1)),
    (Alignment.topCenter, Alignment.bottomRight, const Offset(0, -1)),
    //
    (Alignment.topRight, Alignment.topLeft, const Offset(1, 0)),
    (Alignment.topRight, Alignment.topCenter, Offset.zero),
    (Alignment.topRight, Alignment.topRight, Offset.zero),
    (Alignment.topRight, Alignment.centerLeft, const Offset(1, 0)),
    (Alignment.topRight, Alignment.center, Offset.zero),
    (Alignment.topRight, Alignment.centerRight, Offset.zero),
    (Alignment.topRight, Alignment.bottomLeft, Offset.zero),
    (Alignment.topRight, Alignment.bottomCenter, const Offset(0, -1)),
    (Alignment.topRight, Alignment.bottomRight, const Offset(0, -1)),
    //
    (Alignment.centerLeft, Alignment.topLeft, Offset.zero),
    (Alignment.centerLeft, Alignment.topCenter, Offset.zero),
    (Alignment.centerLeft, Alignment.topRight, const Offset(-1, 0)),
    (Alignment.centerLeft, Alignment.centerLeft, Offset.zero),
    (Alignment.centerLeft, Alignment.center, Offset.zero),
    (Alignment.centerLeft, Alignment.centerRight, const Offset(-1, 0)),
    (Alignment.centerLeft, Alignment.bottomLeft, Offset.zero),
    (Alignment.centerLeft, Alignment.bottomCenter, Offset.zero),
    (Alignment.centerLeft, Alignment.bottomRight, const Offset(-1, 0)),
    //
    (Alignment.center, Alignment.topLeft, Offset.zero),
    (Alignment.center, Alignment.topCenter, Offset.zero),
    (Alignment.center, Alignment.topRight, Offset.zero),
    (Alignment.center, Alignment.centerLeft, Offset.zero),
    (Alignment.center, Alignment.center, Offset.zero),
    (Alignment.center, Alignment.centerRight, Offset.zero),
    (Alignment.center, Alignment.bottomLeft, Offset.zero),
    (Alignment.center, Alignment.bottomCenter, Offset.zero),
    (Alignment.center, Alignment.bottomRight, Offset.zero),
    //
    (Alignment.centerRight, Alignment.topLeft, const Offset(1, 0)),
    (Alignment.centerRight, Alignment.topCenter, Offset.zero),
    (Alignment.centerRight, Alignment.topRight, Offset.zero),
    (Alignment.centerRight, Alignment.centerLeft, const Offset(1, 0)),
    (Alignment.centerRight, Alignment.center, Offset.zero),
    (Alignment.centerRight, Alignment.centerRight, Offset.zero),
    (Alignment.centerRight, Alignment.bottomLeft, const Offset(1, 0)),
    (Alignment.centerRight, Alignment.bottomCenter, Offset.zero),
    (Alignment.centerRight, Alignment.bottomRight, Offset.zero),
    //
    (Alignment.bottomLeft, Alignment.topLeft, const Offset(0, 1)),
    (Alignment.bottomLeft, Alignment.topCenter, const Offset(0, 1)),
    (Alignment.bottomLeft, Alignment.topRight, Offset.zero),
    (Alignment.bottomLeft, Alignment.centerLeft, Offset.zero),
    (Alignment.bottomLeft, Alignment.center, Offset.zero),
    (Alignment.bottomLeft, Alignment.centerRight, const Offset(-1, 0)),
    (Alignment.bottomLeft, Alignment.bottomLeft, Offset.zero),
    (Alignment.bottomLeft, Alignment.bottomCenter, Offset.zero),
    (Alignment.bottomLeft, Alignment.bottomRight, const Offset(-1, 0)),
    //
    (Alignment.bottomCenter, Alignment.topLeft, const Offset(0, 1)),
    (Alignment.bottomCenter, Alignment.topCenter, const Offset(0, 1)),
    (Alignment.bottomCenter, Alignment.topRight, const Offset(0, 1)),
    (Alignment.bottomCenter, Alignment.centerLeft, Offset.zero),
    (Alignment.bottomCenter, Alignment.center, Offset.zero),
    (Alignment.bottomCenter, Alignment.centerRight, Offset.zero),
    (Alignment.bottomCenter, Alignment.bottomLeft, Offset.zero),
    (Alignment.bottomCenter, Alignment.bottomCenter, Offset.zero),
    (Alignment.bottomCenter, Alignment.bottomRight, Offset.zero),
    //
    (Alignment.bottomRight, Alignment.topLeft, Offset.zero),
    (Alignment.bottomRight, Alignment.topCenter, const Offset(0, 1)),
    (Alignment.bottomRight, Alignment.topRight, const Offset(0, 1)),
    (Alignment.bottomRight, Alignment.centerLeft, const Offset(1, 0)),
    (Alignment.bottomRight, Alignment.center, Offset.zero),
    (Alignment.bottomRight, Alignment.centerRight, Offset.zero),
    (Alignment.bottomRight, Alignment.bottomLeft, const Offset(1, 0)),
    (Alignment.bottomRight, Alignment.bottomCenter, Offset.zero),
    (Alignment.bottomRight, Alignment.bottomRight, Offset.zero),
  ]) {
    test(
      'default portal spacing, no diagonals - $child -$portal',
      () => expect(const FPortalSpacing(1).call(child, portal), expected),
    );
  }
}
